config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end
  namespace :admin do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "_about"
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  get "/orders/thanks" => "public/orders#thanks", as: "public_orders_thanks"
  scope module: :public do
    resources :orders, only: [:new, :create, :index, :show]
  end
  post "/orders/confirm" => "public/orders#confirm", as: "public_orders_confirm"
  
  delete "/cart_items/destroy_all" => "public/cart_items#destroy_all", as: "cart_items_destroy_all"
  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
  end
  get "/customers/withdraw_check" => "public/customers#withdraw_check", as: "withdraw_check"
  patch "/customers/withdraw" => "public/customers#withdraw", as: "withdraw"

  scope module: :public do
    resources :registrations, only: [:new, :create]
  end
  scope module: :public do
    resources :items, only: [:index, :show]
  end
  root to: 'public/homes#top'
  get "/about" => "public/homes#about", as: "public_about"

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code  + ' ' + address + ' ' + name
  end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  
  def with_tax_price
    (price*1.1).floor
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered:4 }
  
  
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum crafting_status: { start_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3, }




end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre = genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10).order(id: "DESC")
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    items = item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @total_cost = 0
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "payment_confirmation"
      @order.order_details.update_all(crafting_status: 1)
    end
    redirect_to admin_order_path(@order)
  end

   def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="mt-5">
    <h4 class="text-center" style="background-color: #dcdcdc; width: 18%;">ジャンル編集</h4>
  </div>
    <div class="col-md-6 mt-5">
      <%= form_with model: @genre, url:admin_genre_path(@genre), method: :patch  do |f|%>
      <span>ジャンル名</span>
      <%= f.text_field :name,class:"ml-5"%>
      <%= f.submit '変更を保存',class:"btn btn-success w-25 text-light ml-5"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="mt-5">
    <h4 class="text-center" style="background-color: #dcdcdc; width: 25%;">ジャンル一覧・追加</h4>
  </div>
  <div class="row">
    <div class="col-md-7 mt-5">
      <%= form_with model: @genre, url:admin_genres_path do |f|%>
      <span>ジャンル名</span>
      <%= f.text_field :name,placeholder:"ジャンル名",class:"ml-5"%>
      <%= f.submit '新規登録',class:"btn btn-success w-25 text-light ml-5"  %>
      <% end %>

      <table class="table w-50 mt-5">
        <tr　class="border-top style:border-light">
          <th bgcolor="#f5f5f5", style="width:60%" class="pl-5">ジャンル</th>
          <th bgcolor="#f5f5f5",></th>
        </tr>

        <% @genres.each do |genre|%>
        <tr class="border-top border-bottom style:border-light">
          <td><%= genre.name%></td>
          <td><%= link_to "編集する",edit_admin_genre_path(genre.id),class:"btn btn-success w-100 text-light" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="d-flex flex-row mt-5 ml-5 pl-3">
    <h4 class="text-center pt-1" style="background-color: #dcdcdc; width: 15%;">注文履歴一覧</h4>
  </div>

  <div class="row" style="margin-top:15px; margin-left:50px;">
    <div class="col-md-10">
      <table class="table">
        <tr　class="border-top">
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-3">購入日時</th>
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-3">購入者</th>
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-3">注文個数</th>
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-3">注文ステータス</th>
        </tr>

        <% @orders.each do |order|%>
          <% @count = 0 %>
          <% order.order_details.each do |order_detail| %>
            <% @count += order_detail.quantity %>
          <% end %>

          <tr class="border-bottom">
            <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'),admin_order_path(order) %></td>
            <td><%= order.customer.first_name %><%= order.customer.last_name %></td>
            <td><%= @count %></td>
            <td><%= order.status_i18n %></td>
          </tr>

        <% end %>
      </table>
      </div>
    </div>

    <div style="margin-left: 45%;" class="mt-3">
    <%= paginate @orders %>
    </div>

  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="mt-5 w-25">
    <h4 class="text-center" style="background-color: #dcdcdc; width: 70%;">商品編集</h4>
  </div>
  
  <<%= form_with model: @item, url:admin_item_path, method: :patch do |f| %>
  <div class="row ml-5 pl-5 mt-5">
    <div class="col-2 ml-4">
      <span class="col-5">商品画像</span>
    </div>
    <div class="col-6 ml-4 pl-4">
      <%= f.file_field :image,accept: "image/*",class:"col-9"%>
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">商品名</span>
    </div>
    <div class="col-6">
      <%= f.text_field :name,placeholder:"商品名",class:"ml-5 col-9"%>
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">商品説明</span>
    </div>
    <div class="col-6">
      <%= f.text_area :introduction,placeholder:"ここに説明文を記述します",class:"ml-5 col-9"%>
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">ジャンル</span>
     </div>
     <div class="col-6 ml-5">
       <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name),style:"width: 500px;" %>
     </div>
   </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">税抜価格</span>
    </div>
    <div class="col-6">
      <%= f.text_field :price,placeholder:"1000",class:"ml-5 col-9"%>円
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4" style="font-size: 15px;">
      <span class="col-5">販売ステータス</span>
    </div>
    <div class="col-6 ml-5">
      <%= f.radio_button :is_active, "true" %>
      <%= f.label :is_active, "販売中",class:"mr-3"%>

      <%= f.radio_button :is_active, "false" %>
      <%= f.label :is_active, "販売停止中" %>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit '変更を保存',class:"btn btn-success text-light mr-5 mt-4",style:"width:15%;"%>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="d-flex flex-row mt-5 ml-5 pl-3">
    <h4 class="text-center pt-1" style="background-color: #dcdcdc; width: 15%;">商品一覧</h4>
    <span style="margin-left: 75%;">
       <%= link_to  new_admin_item_path do%>
       <i class="fas fa-plus-circle fa-3x" style="color: #9e9e9e;"></i>

      <% end %>
    </span>
  </div>

  <div class="row">
    <div class="col-md-11 ml-5 mt-4">
      <table class="table">
        <tr　class="border-top">
          <th bgcolor="#f5f5f5", style="width:15%" class="pl-3">商品ID</th>
          <th bgcolor="#f5f5f5", style="width:30%" class="pl-3">商品名</th>
          <th bgcolor="#f5f5f5", style="width:15%" class="pl-3">税抜価格</th>
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-3">ジャンル</th>
          <th bgcolor="#f5f5f5", style="width:15%" class="pl-3">ステータス</th>
        </tr>

        <% @items.each do |item|%>
          <% if item.is_active ==true %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id) %></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name%></td>
            <td><strong style="color:#3cb371;">販売中</strong></td>
          </tr>
          <% else%>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id) %></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name%></td>
            <td><strong style="color: #808080;">販売停止中</strong></td>
          </tr>
          <% end %>
        <% end %>
      </table>
      </div>
    </div>

    <div style="margin-left: 45%;" class="mt-3">
    <%= paginate @items %>
    </div>

  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="mt-5 w-25">
    <h4 class="text-center" style="background-color: #dcdcdc; width: 70%;">商品新規登録</h4>
  </div>
  <%= form_with model: @item, url:admin_items_path do |f| %>

  <div class="row ml-5 pl-5 mt-5">
    <div class="col-2 ml-4">
      <span class="col-5">商品画像</span>
    </div>
    <div class="col-6 ml-4 pl-4">
      <%= f.file_field :image,accept: "image/*",class:"col-9"%>
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">商品名</span>
    </div>
    <div class="col-6">
      <%= f.text_field :name,placeholder:"商品名",class:"ml-5 col-9"%>
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">商品説明</span>
    </div>
    <div class="col-6">
      <%= f.text_area :introduction,placeholder:"ここに説明文を記述します",class:"ml-5 col-9"%>
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">ジャンル</span>
     </div>
     <div class="col-6 ml-5">
       <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {include_blank: "-- 選択してください --" }, style:"width: 75%; font-size: 15px;"%>
     </div>
   </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4">
      <span class="col-5">税抜価格</span>
    </div>
    <div class="col-6">
      <%= f.text_field :price,placeholder:"1000",class:"ml-5 col-9"%>円
    </div>
  </div>

  <div class="row ml-5 pl-5 mt-3">
    <div class="col-2 ml-4" style="font-size: 15px;">
      <span class="col-5">販売ステータス</span>
    </div>
    <div class="col-6 ml-5">
      <%= f.radio_button :is_active, "true" %>
      <%= f.label :is_active, "販売中",class:"mr-3"%>

      <%= f.radio_button :is_active, "false" %>
      <%= f.label :is_active, "販売停止中" %>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit '新規登録',class:"btn btn-success text-light mr-5 mt-4",style:"width:15%;"%>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="d-flex flex-row mt-5 ml-5 pl-3">
    <h4 class="text-center" style="background-color: #dcdcdc; width: 15%;">商品詳細</h4>
  </div>

  <div class="row" style="margin-top: 80px;">
    <div class="col-md-3">
      <%= image_tag @item.image,width: '300px', height: '200px' %>
    </div>

    <div class="col-md-8 offset-md-1">
      <div class="row">
        <div class="col-2">
          <span>商品名</span>
        </div>
        <div class="col-7">
          <span style="font-size: 17px;"><%= @item.name%></span>
        </div>
      </div>

      <div class="row" style="margin-top: 20px;">
        <div class="col-2" >
          <span>商品説明</span>
        </div>
        <div class="col-7">
          <span class="text-break" style="font-size: 17px;"><%= @item.introduction%></span>
        </div>
      </div>

      <div class="row" style="margin-top: 50px;">
        <div class="col-2">
          <span>ジャンル</span>
        </div>
        <div class="col-7">
          <span style="font-size: 17px;"><%= @item.genre.name%></span>
        </div>
      </div>

      <div class="row" style="margin-top: 20px;">
        <div class="col-2">
          <span>税込価格</br>(税抜価格)</span>
        </div>
        <div class="col-7 my-auto">
          <span style="margin-right: 5px; font-size: 20px;"><%= (@item.price*1.1).floor.to_s(:delimited) %></span><span style="margin-right: 5px; font-size: 20px;">(<%= @item.price.to_s(:delimited) %>)</span><span>円</span>
        </div>
      </div>

      <% if @item.is_active ==true %>
      <div class="row" style="margin-top: 20px;">
        <div class="col-2">
          <span style="font-size:13px;">販売ステータス</span>
        </div>
        <div class="col-7 my-auto">
          <strong style="color:#3cb371; font-size: 20px;">販売中</strong>
        </div>
      </div>

      <% else%>
      <div class="row" style="margin-top: 20px;">
        <div class="col-2">
          <span style="font-size:13px;">販売ステータス</span>
        </div>
        <div class="col-7">
          <strong style="color: #808080; font-size: 20px;">販売停止中</strong>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "編集する", edit_admin_item_path(@item),class:"btn btn-success text-light mr-5 mt-4 ",style:"width:130px;" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container" style="margin-left:70px;">
  <div class="d-flex flex-row mt-5 ml-5 pl-3">
    <h4 class="text-center pt-1" style="background-color: #dcdcdc; width: 20%;">注文履歴詳細</h4>
  </div>

  <div class="row" style="margin-top:10px;">
    <div class="col-md-12">
      <b style="font-size:20px; margin-right:110px;">購入者</b>
      <span style="font-size:20px;"><%= link_to (@order.customer.first_name + " " + @order.customer.last_name), admin_customer_path(@order.customer_id )%></span>
    </div>

    <div class="col-md-12" style="margin-top:10px;">
      <b style="font-size:20px; margin-right:110px;">注文日</b>
      <span style="font-size:20px;"><%= @order.created_at.strftime('%Y/%m/%d') %></span>
    </div>

    <div class="col-md-12" style="margin-top:10px;">
      <b style="font-size:20px; margin-right:110px;">発送先</b>
      <span style="font-size:20px;">
          〒<%= (@order.shipping_postal_code.to_s.insert(3, "-") + " " + @order.shipping_address )%> </br>
          <span style="margin-left:175px;"></span><%= @order.shipping_name %>
      </span>
    </div>

    <div class="col-md-12" style="margin-top:10px;">
      <b style="font-size:20px; margin-right:90px;">支払方法</b>
      <span style="font-size:20px;"><%= @order.payment_method_i18n %></span>
    </div>

    <%= form_with model: @order, url:admin_order_path(@order), method: :patch  do |f|%>
      <div class="col-md-12" style="margin-top:10px;">
        <b style="font-size:20px; margin-right:30px;">注文ステータス</b>
        <span style="font-size:17px;"><%= f.select :status, Order.statuses_i18n.invert %></span>
        <span style="margin-left:30px;"><%= f.submit '更新',class:"btn btn-success text-light",style:"font-size:15px;" %></span>
      </div>
    <% end %>
  </div>

  <div class="row" style="margin-top:25px;">
    <div class="col-md-9">
      <table class="table">
        <tr　class="border-top">
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-3">商品名</th>
          <th bgcolor="#f5f5f5", style="width:20%" class="pl-3">単価( 税込 )</th>
          <th bgcolor="#f5f5f5", style="width:15%" class="pl-3">数量</th>
          <th bgcolor="#f5f5f5", style="width:15%" class="pl-3">小計</th>
          <th bgcolor="#f5f5f5", style="width:20%" class="pl-3">製作ステータス</th>
          <th bgcolor="#f5f5f5", style="width:15%" class="pl-3"></th>
        </tr>

        <% @order.order_details.each do |order_detail|%>
          <tr class="border-bottom">
            <td><span><%= order_detail.item.name%></span></td>
            <td><span><%= order_detail.purchase_price.to_s(:delimited) %></span></td>
            <td><%= order_detail.quantity %></td>
            <% sub_total = 0 %>
            <% sub_total = order_detail.purchase_price * order_detail.quantity %>
            <td><%= sub_total.to_s(:delimited) %></td>
            <% @total_cost += sub_total %>
            <%= form_with model: order_detail, url:admin_order_detail_path(order_detail), method: :patch  do |f|%>
              <td><%= f.select :crafting_status, OrderDetail.crafting_statuses_i18n.invert  %></td>
              <td><%= f.submit '更新',class:"btn btn-success text-light",style:"font-size:15px;" %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="col-md-3" style="margin-top:auto">
      <div class="d-flex">
        <div style="width:60%;"><b style="font-size:20px;">商品合計</b></div>
        <div style="width:40%;"><span style="font-size:20px; display:block; text-align:right;"><%= @total_cost.to_s(:delimited) %>円</span></div>
      </div>

      <div class="d-flex">
        <div style="width:60%;"><b style="font-size:20px;">送料</b></div>
        <div style="width:40%;"><span style="font-size:20px; display:block; text-align:right;"><%= @order.carriage %>円</span></div>
      </div>

      <div class="d-flex">
        <div style="width:60%;"><b style="font-size:20px;">請求金額合計</b></div>
        <div style="width:40%;"><b  style="font-size:20px; display:block; text-align:right;"><%= (@total_cost + @order.carriage).to_s(:delimited) %>円</b></div>
      </div>
    </div>
  </div>
</div>