config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :order_details, only: [:update]
  end
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end
  namespace :admin do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "_about"
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  get "/orders/thanks" => "public/orders#thanks", as: "public_orders_thanks"
  scope module: :public do
    resources :orders, only: [:new, :create, :index, :show]
  end
  post "/orders/confirm" => "public/orders#confirm", as: "public_orders_confirm"
  
  delete "/cart_items/destroy_all" => "public/cart_items#destroy_all", as: "cart_items_destroy_all"
  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
  end
  get "/customers/withdraw_check" => "public/customers#withdraw_check", as: "withdraw_check"
  patch "/customers/withdraw" => "public/customers#withdraw", as: "withdraw"

  scope module: :public do
    resources :registrations, only: [:new, :create]
  end
  scope module: :public do
    resources :items, only: [:index, :show]
  end
  root to: 'public/homes#top'
  get "/about" => "public/homes#about", as: "public_about"

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code  + ' ' + address + ' ' + name
  end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  
  def with_tax_price
    (price*1.1).floor
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered:4 }
  
  
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum crafting_status: { start_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3, }




end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10).order(id: "DESC")
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    items = item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", admin_root_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <container style="height: 20%;">
    <% if admin_signed_in? %>
      <div class="d-flex flex-row" style="height: 90px;">
        <div class="col-4">
          <h2 style="margin-top:10px;"><%= link_to admin_root_path do%> <%= image_tag "image_logo",width: '250px', height: '70px'%> <% end %></h2>
        </div>
        <div class="col-8 d-flex flex-row" style="margin-left:7%; margin-top:10px;">
          <li class="col-md-2 px-0" style="list-style:none;"><%= link_to "商品一覧",admin_items_path,class:"btn btn-success text-light",style:"width:80%;"%></li>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "会員一覧",admin_customers_path,class:"btn btn-success text-light",style:"width:80%;"%><liv>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "注文履歴一覧",admin_root_path,class:"btn btn-success text-light",style:"width100%; font-size:15px; height:37px;"%></li>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "ジャンル一覧",admin_genres_path,class:"btn btn-success text-light",style:"width:80%; font-size:15px; height:37px;"%></li>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "ログアウト",destroy_admin_session_path,method: :delete,class:"btn btn-success text-light",style:"width:80%;"%></li>
        </div>
      </div>
      <div style="border-bottom: solid 2px black;">
          <%= form_with url:items_path, method: :get do |f| %>
            <%= f.text_field :item_name ,placeholder: "Search", style:"margin-left:1200px; margin-bottom:10px; "%>
          <% end %>
      </div>
    <% elsif customer_signed_in? %>
      <div class="d-flex flex-row" style="height: 90px;">
        <div class="col-5">
          <h2 style="margin-top:10px;"><%= link_to root_path do%> <%= image_tag "image_logo",width: '250px', height: '70px'%> <% end %> <span style="font-size:20px; margin-left:30px;">ようこそ、<%= current_customer.first_name%>さん！</span></h2>
        </div>
        <div class="col-8 d-flex flex-row" style="margin-left:13%; margin-top:10px;">
          <li class="col-md-2 px-0" style="list-style:none;"><%= link_to "マイページ",customers_path,class:"btn btn-success text-light",style:"width:80%;"%></li>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "商品一覧",items_path,class:"btn btn-success text-light",style:"width:70%;"%><liv>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "カート",cart_items_path,class:"btn btn-success text-light",style:"width:80%; font-size:15px; height:37px;"%></li>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "ログアウト",destroy_customer_session_path,method: :delete,class:"btn btn-success text-light",style:"width:80%;"%></li>
        </div>
      </div>
      <div style="border-bottom: solid 2px black;">
          <%= form_with url:items_path, method: :get do |f| %>
            <%= f.text_field :item_name ,placeholder: "Search" ,style:"margin-left:1200px; margin-bottom:10px; "%>
          <% end %>
      </div>
    <% else %>
     <div class="d-flex flex-row" style="height: 90px;">
        <div class="col-4">
          <h2 style="margin-top:10px;"><%= link_to root_path do %> <%= image_tag "image_logo",width: '250px', height: '70px'%> <% end %> </h2>
        </div>
        <div class="col-8 d-flex flex-row" style="margin-left:23%; margin-top:10px;">
          <li class="col-md-2 px-0" style="list-style:none;"><%= link_to "About",public_about_path,class:"btn btn-success text-light",style:"width:70%;"%></li>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "商品一覧",items_path,class:"btn btn-success text-light",style:"width:70%;"%><liv>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "新規登録",new_customer_registration_path,class:"btn btn-success text-light",style:"width:70%; font-size:15px; height:37px;"%></li>
          <li class="col-2 px-0" style="list-style:none;"><%= link_to "ログイン",new_customer_session_path,class:"btn btn-success text-light",style:"width:70%; font-size:15px; height:37px;"%></li>
        </div>
      </div>
      <div class="search" style="border-bottom: solid 2px black;">
          <%= form_with url:items_path, method: :get do |f| %>
            <%= f.text_field :item_name ,placeholder: "Search" ,style:"margin-left:1200px; margin-bottom:10px; "%>
          <% end %>
      </div>
    <% end %>
    </container>


    <div style="min-height: 500px;">
      <%= yield %>
    </div>

    <footer style="min-height: 100px; background-color: #dcdcdc;">
      <div class="mt-5">
        <P class="text-center" style="padding-top: 50px; font-size:17px;">CopyRight Infratop.inc</P>
      </div>
    </footer>
  </body>
</html>